; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppId={{BCE9D30E-68DD-419C-8DC0-14B5FED9B8BE}
AppName=Windows CVE
AppVerName=Windows CVE Version 0.7.2
AppPublisher=NMSU/UIDAHO  CVE Project
AppPublisherURL=http://cve.sf.net/
AppSupportURL=http://cve.sf.net/
AppUpdatesURL=http://cve.sf.net/
DefaultDirName=C:\Program Files\CVE
DefaultGroupName=CVE
AllowNoIcons=yes
OutputBaseFilename=setup-cve
Compression=lzma
SolidCompression=yes
;;;AlwaysCreateUninstallIcon=yes
; uncomment the following line if you want your installation to run on NT 3.51 too.
; MinVersion=4,3.51

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; MinVersion: 4,4

[Files]
Source: "\cve\bin\cve.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "\cve\bin\*.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "\cve\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "\cve\bin\*.cmd"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "\cve\README.txt"; DestDir: "{app}"; Flags: isreadme
Source: "\cve\userguid.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "\cve\wicont.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "\cve\wiconx.exe"; DestDir: "{app}"; Flags: ignoreversion

Source: "\cve\dat\*.*"; DestDir: "{app}\dat"; Flags: ignoreversion
Source: "\cve\dat\3dmodels\*.*"; DestDir: "{app}\dat\3dmodels"; Flags: ignoreversion
Source: "\cve\dat\help\*.*"; DestDir: "{app}\dat\help"; Flags: ignoreversion
Source: "\cve\dat\images\*.*"; DestDir: "{app}\dat\images"; Flags: ignoreversion
Source: "\cve\dat\images\letters\*.*"; DestDir: "{app}\dat\images\letters"; Flags: ignoreversion
Source: "\cve\dat\scratch\*.*"; DestDir: "{app}\dat\scratch"; Flags: ignoreversion
Source: "\cve\dat\textures\*.*"; DestDir: "{app}\dat\textures"; Flags: ignoreversion

;Source: "\cve\dat\users\tux\*.*"; DestDir: "{app}\dat\users\tux"; Flags: ignoreversion
Source: "\cve\dat\users\tux\quests\*.*"; DestDir: "{app}\dat\users\tux\quests"; Flags: ignoreversion
Source: "\cve\dat\users\dog\*.*"; DestDir: "{app}\dat\users\dog"; Flags: ignoreversion
Source: "\cve\dat\users\sid\*.*"; DestDir: "{app}\dat\users\sid"; Flags: ignoreversion
;Source: "\cve\dat\users\tausha\*.*"; DestDir: "{app}\dat\users\tausha"; Flags: ignoreversion
Source: "\cve\dat\users\guest\*.*"; DestDir: "{app}\dat\users\guest"; Flags: ignoreversion
;Source: "\cve\dat\users\cjeffery\*.*"; DestDir: "{app}\dat\users\cjeffery"; Flags: ignoreversion

Source: "\cve\dat\nmsu\*.*"; DestDir: "{app}\dat\nmsu"; Flags: ignoreversion
Source: "\cve\dat\nmsu\agents\echo\*.*"; DestDir: "{app}\dat\nmsu\agents\echo"; Flags: ignoreversion
Source: "\cve\dat\nmsu\agents\gc\*.*"; DestDir: "{app}\dat\nmsu\agents\gc"; Flags: ignoreversion
Source: "\cve\dat\nmsu\agents\secretary\*.*"; DestDir: "{app}\dat\nmsu\agents\secretary"; Flags: ignoreversion
Source: "\cve\dat\nmsu\edges\*.dat"; DestDir: "{app}\dat\nmsu\edges"; Flags: ignoreversion
Source: "\cve\dat\nmsu\images\*.*"; DestDir: "{app}\dat\nmsu\images"; Flags: ignoreversion
Source: "\cve\dat\nmsu\nodes\*.dat"; DestDir: "{app}\dat\nmsu\nodes"; Flags: ignoreversion
Source: "\cve\dat\nmsu\roomdat\*.*"; DestDir: "{app}\dat\nmsu\roomdat"; Flags: ignoreversion
Source: "\cve\dat\nmsu\edgedat\*.*"; DestDir: "{app}\dat\nmsu\edgedat"; Flags: ignoreversion
Source: "\cve\dat\nmsu\sounds\*.*"; DestDir: "{app}\dat\nmsu\sounds"; Flags: ignoreversion
Source: "\cve\dat\nmsu\texsmall\*.*"; DestDir: "{app}\dat\nmsu\texsmall"; Flags: ignoreversion
Source: "\cve\dat\nmsu\textures\*.*"; DestDir: "{app}\dat\nmsu\textures"; Flags: ignoreversion
Source: "\cve\dat\\nmsu\whiteboards\*.*"; DestDir: "{app}\dat\nmsu\whiteboards"; Flags: ignoreversion

Source: "\cve\dat\uidaho\*.*"; DestDir: "{app}\dat\uidaho"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\edges\*.*"; DestDir: "{app}\dat\uidaho\edges"; Flags: ignoreversion
Source: "\cve\dat\uidaho\images\*.*"; DestDir: "{app}\dat\uidaho\images"; Flags: ignoreversion
Source: "\cve\dat\uidaho\roomdat\*.*"; DestDir: "{app}\dat\uidaho\roomdat"; Flags: ignoreversion
Source: "\cve\dat\uidaho\edgedat\*.*"; DestDir: "{app}\dat\uidaho\edgedat"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\basement\*.*"; DestDir: "{app}\dat\uidaho\room\basement"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\brent\*.*"; DestDir: "{app}\dat\uidaho\room\brent"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\corridor1\*.*"; DestDir: "{app}\dat\uidaho\room\corridor1"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\corridor2\*.*"; DestDir: "{app}\dat\uidaho\room\corridor2"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\corridor3\*.*"; DestDir: "{app}\dat\uidaho\room\corridor3"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\csac\*.*"; DestDir: "{app}\dat\uidaho\room\csac"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\elevator\*.*"; DestDir: "{app}\dat\uidaho\room\elevator"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\ground\*.*"; DestDir: "{app}\dat\uidaho\room\ground"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb013\*.*"; DestDir: "{app}\dat\uidaho\room\jeb013"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb025\*.*"; DestDir: "{app}\dat\uidaho\room\jeb025"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb104\*.*"; DestDir: "{app}\dat\uidaho\room\jeb104"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb221\*.*"; DestDir: "{app}\dat\uidaho\room\jeb221"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb222\*.*"; DestDir: "{app}\dat\uidaho\room\jeb222"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb230\*.*"; DestDir: "{app}\dat\uidaho\room\jeb230"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb236\*.*"; DestDir: "{app}\dat\uidaho\room\jeb236"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb237\*.*"; DestDir: "{app}\dat\uidaho\room\jeb237"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb328\*.*"; DestDir: "{app}\dat\uidaho\room\jeb328"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jeb331\*.*"; DestDir: "{app}\dat\uidaho\room\jeb331"; Flags: ignoreversion
;Source: "\cve\dat\uidaho\room\jebstair\*.*"; DestDir: "{app}\dat\uidaho\room\jebstair"; Flags: ignoreversion
Source: "\cve\dat\uidaho\textures\*.*"; DestDir: "{app}\dat\uidaho\textures"; Flags: ignoreversion
Source: "\cve\dat\uidaho\texsmall\*.*"; DestDir: "{app}\dat\uidaho\texsmall"; Flags: ignoreversion


[INI]
Filename: "{app}\cve.url"; Section: "InternetShortcut"; Key: "URL"; String: "http://cve.sf.net"

[Icons]
Name: "{group}\Windows CVE"; Filename: "{app}\bin\cve.exe"
Name: "{group}\User Guid"; Filename: "{app}\userguid.pdf"
Name: "{group}\{cm:UninstallProgram,Windows CVE}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\Windows CVE"; Filename: "{app}\bin\cve.exe"; MinVersion: 4,4; Tasks: desktopicon

[Run]
Filename: "{app}\bin\cve.exe"; Description: "Launch Windows CVE"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\cve.url"

[Registry]
; ???
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; ValueName: "{app}\bin\cve.exe"; ValueType: "string"; ValueData: "WINXPSP2"; Flags : createvalueifdoesntexist uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; ValueName: "{app}\wiconx.exe"; ValueType: "string"; ValueData: "WINXPSP2"; Flags : createvalueifdoesntexist uninsdeletekey

